### PR TITLE
Updating to SQ 5.6 / SJava 4.0

### LINKED ISSUE #5: Fix compatibility with Java Plugin 4.0
The Java plugin 4.0 slightly changed its API in order to align with new SonarQube LTS API. The Ccobertura plugin, relying on the Java Analyzer, has to adapt consequently, as analyzes will fail. 

For the change of API, see line [Line #40](https://github.com/SonarSource/sonar-java/blob/5bb12a036d6001ed0e5853a39be21929f29a31ad/java-frontend/src/main/java/org/sonar/plugins/java/api/JavaResourceLocator.java#L40) of the Java plugin. Prior to the change, the method `findResourceByClassName()` was returning a `org.sonar.api.resources.Resource`. Now it is returning an `org.sonar.api.batch.fs.InputFile`.

The method is used in the [CoberturaReportParser, Line #82](https://github.com/SonarQubeCommunity/sonar-cobertura/blob/c081ed4ca610e24d4ec95edc3bbd61c9dab93ba7/src/main/java/org/sonar/plugins/cobertura/CoberturaReportParser.java#L82).

```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.1-build231:sonar (default-cli) 
on project HeadShot-java8: Execution default-cli of goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.1-build231:sonar failed: 
An API incompatibility was encountered while executing org.sonarsource.scanner.maven:sonar-maven-plugin:3.1-build231:sonar: java.lang.NoSuchMethodError:
org.sonar.plugins.java.api.JavaResourceLocator.findResourceByClassName(Ljava/lang/String;)Lorg/sonar/api/resources/Resource;

...

Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findResourceByClassName(Ljava/lang/String;)Lorg/sonar/api/resources/Resource;
```

### PR DESCRIPTION
**Pull request by bguerin**
Fix #5

### CODE REVIEW

**Comment by m-g-sonar** [comment]
Hey, in order to have the ITs passing, you should change the `travis.yml` file at the root folder to modify version of Java (from 7 to 8), as well as version of SQ.

The plugin currently doesn't have a community maintainer. Would you be interested? (Requires max 1 or 2 release/year)

**Comment by bguerin** [comment]
@m-g-sonar I made change in .travis.yml, but build is still failling, I guess because .m2 cache is not up to date ... How can I fix this ? (if I am able to ...)

For being a maintainer, I am just a user of SonarQube, not a plugin developer, I know nothing about SonarQube code, nor its plugins ecosystem ...

**Comment by m-g-sonar** [comment]
Okay @bguerin, I'll have a look!

About being maintainer, no worries, I was just asking! :)

**Comment by m-g-sonar** [comment]
@bguerin: I investigate the issue on travis. There is still 2 things to be fixed: 

- In order to have the id not failing because of its size, it has to be run in batch mode. To do so, simply add `-B` or `--batch-mode` in the travis.sh file, in the line running the IT: https://github.com/SonarQubeCommunity/sonar-cobertura/blob/master/travis.sh#L23
- After fixing that, another issue is going to appear, related to the fact that the Cobertura plugin now needs to provide `common-io` and `common-lang`.

I'll let you fix your PR accordingly.

**Comment by bguerin** [comment]
@m-g-sonar : thanks for these informations ! I will update my PR soon

**Comment by bguerin** [comment]
CI fixed, many thanks for your help and your time !

**Comment by ceagan** [comment]
I tested this fix on our Sonar installation and I can confirm that it is working for us now. Thanks!

**Comment by m-g-sonar** [comment]
Okay, I'm going to merge your PR, and start a RFF (Request For Feedback) thread for a new release.
Thanks for the fix.

Finally, please note that next release will have to be made by the community, as Sonarsource is not maintaining this plugin anymore.

**Comment by m-g-sonar** [comment]
RFF for version 1.7 has started on this thread: https://groups.google.com/d/topic/sonarqube/AGGQJLa1KZA/discussion

**Pull request merged**
